add pericardium model boundary force
drwells/fiddle pull request #79
Opened 2022-07-23 00:15 UTC by marshallrdavey

fixes #78 

Does this works the way I think it does where `normal_vector` and `get_velocity_values` are computed at the quadrature points on the face?

2022-07-23 14:03 UTC, drwells requested changes
> Does this works the way I think it does where normal_vector and get_velocity_values are computed at the quadrature points on the face?

Yes.

We also need a test.

2022-07-23 14:03 UTC, drwells commented on source/mechanics/force_contribution_lib.cc
> +        std::copy(this->scratch_qp_values.begin(),                                // copy forces into output
can we skip these comments? They just duplicate what is in the code.

2022-07-23 14:03 UTC, drwells commented on source/mechanics/force_contribution_lib.cc
> +            fe_values.normal_vector(i);
These should be the deformed normal vectors provided by `MechanicsValues`, not the reference normal vectors provided by `FEValues`.

2022-07-23 14:03 UTC, drwells commented on source/mechanics/force_contribution_lib.cc
> +    return MechanicsUpdateFlags::update_velocity_values;
We should also request the deformed normal vectors here.

2022-07-29 14:49 UTC, drwells commented
Take a look at `tests/mechanics/spring_01.cc`: we should just print some values and call it a day.

2022-08-03 16:02 UTC, marshallrdavey commented
@drwells this has a test now, do you want me to write another test within the same file that has more complex movement (e.g. contraction towards the center)?

2022-08-03 20:39 UTC, drwells commented
It's probably fine as-is.

2022-08-03 20:39 UTC, drwells approved these changes

2022-08-03 20:39 UTC, merged